apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.componentNames.certSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
type: Opaque
stringData:
  server.pem: |
{{ .Values.secrets.certPem | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.componentNames.passwordDbSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
type: Opaque
stringData:
  password.db: |
{{ .Values.secrets.passwordDb | indent 4 }}
