apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.componentNames.coordinatorDataPvc }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.coordinatorLabels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.coordinator.data.size | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.componentNames.coordinatorHeapdumpPvc }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.coordinatorLabels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.coordinator.heapdump.size | quote }}
